### ISSUE TITLE
Integrate the standard unit-test suite

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/build-tools#3]
Consisting of Mocha, Chai and JSDom...

**Comment by Inkdpixels** [comment]
Added in 876cd7a7 - Still open:
- Registration of compilers as in [link](https://github.com/reduct/assembler/blob/b84285717d2e94028dc2f900601748174945a81f/package.json#L7) (Haven't found a way to plug them in via the node API)
- Declaration of process values, as of now I've changed the if condition [from](https://github.com/reduct/assembler/blob/b84285717d2e94028dc2f900601748174945a81f/Src/Assembler.js#L78) [to](https://github.com/reduct/assembler/blob/refactoring/api/Src/Assembler.js#L77)

@akoenig

**Comment by akoenig** [comment]
@Inkdpixels I'm cool with teh change, but would suggest to change the condition to something like this:

In `build-tools`:

```js
process.title = 'reduct';
```

and in the respective module:

```js
if (process && process.title && !!~process.title.indexOf('reduct')) {
    ...
}
```

**Comment by Inkdpixels** [comment]
@akoenig Done in ceca8164 and of course changed also in the assembler refactoring branch.

**Comment by akoenig** [comment]
Regarding hooking the transpiler: I guess that requiring the transpiler is enough. Just perform a `require('babel/register')`.

**Comment by Inkdpixels** [comment]
Unfortunately this doesn't work - I am requiring it at the top level.

But yeah, someone also stated that, and this might be related with #7.
https://github.com/reduct/build-tools/blob/master/Bin/Reduct.js#L3

**Comment by akoenig** [comment]
Ah, read #7 just now :)
